### ISSUE TITLE
trim tokens

### ISSUE THREAD

**Issue by missinglink** [pelias/model#16]
migrating issue https://github.com/pelias/suggester-pipeline/issues/5 to this repo

**Comment by missinglink** [comment]
http://pelias.mapzen.com/doc?id=osmnode:2235377518

```json
"text": "Nobis \"the best pizza, Monte di Procida, NAPOLI"
```

**Comment by missinglink** [comment]
had a think about this, we *could* easily add a `transform.trim()` function to all the string `getter/setter` functions but my feeling is that the importers should take responsibility for performing string operations on the data, it's not really the responsibility of this repo to do that; although we do in some cases `lowercase` or `uppercase` for consistency (eg. for alpha3).

thoughts?

**Comment by trescube** [comment]
Don't the ES analyzers we employ trim the tokens?

**Comment by orangejulius** [comment]
@trescube yes, but then the documents returned by ES would still have whitespace in them.

The openaddresses importer will, as of pelias/openaddresses#31, have whitespace trimming fully taken care of. This is mostly so that it can guarantee all records that are inserted into Elasticsearch are valid, and don't have fields that consist entirely of whitespace. So it seems like whitespace trimming is important for importers to do. That said, just trimming whitespace is pretty easy, so doing it everwhere isn't the worst. I definitely don't think we should trim any other characters.

**Comment by missinglink** [comment]
this issue is old and seems to be a low priority.

as discussed above, it would be best to fix data in the source importer rather than in the model itself.
